ALTER TABLE passenger
    MODIFY COLUMN passenger_name VARCHAR(255) NOT NULL,
    ADD COLUMN email VARCHAR(255) NOT NULL,
    ADD COLUMN password VARCHAR(255) NOT NULL,
    ADD COLUMN phone_number VARCHAR(255) NOT NULL;